// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.API.Models.Context;

#nullable disable

namespace Server.API.Migrations
{
    [DbContext(typeof(StoriContext))]
    [Migration("20250507223851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAward", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("AwardId")
                        .HasColumnType("int")
                        .HasColumnName("award_id");

                    b.HasKey("BookId", "AwardId")
                        .HasName("PK__Book_Award");

                    b.HasIndex("AwardId");

                    b.ToTable("Book_Award", (string)null);
                });

            modelBuilder.Entity("BookCharacter", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int")
                        .HasColumnName("character_id");

                    b.HasKey("BookId", "CharacterId")
                        .HasName("PK__Book_Character");

                    b.HasIndex("CharacterId");

                    b.ToTable("Book_Character", (string)null);
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.HasKey("GenreId", "BookId")
                        .HasName("PK__Book_Genre");

                    b.HasIndex("BookId");

                    b.ToTable("Book_Genre", (string)null);
                });

            modelBuilder.Entity("BookSetting", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("SettingId")
                        .HasColumnType("int")
                        .HasColumnName("setting_id");

                    b.HasKey("BookId", "SettingId")
                        .HasName("PK__Book_Setting");

                    b.HasIndex("SettingId");

                    b.ToTable("Book_Setting", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Award");

                    b.ToTable("Award", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookFormat")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("book_format");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("book_id");

                    b.Property<string>("CoverImg")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("cover_img");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Edition")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("edition");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("isbn");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("language");

                    b.Property<int?>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("pages");

                    b.Property<DateOnly?>("PublishDate")
                        .HasColumnType("date")
                        .HasColumnName("publish_date");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Series")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("series");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Book");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Character");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Genre");

                    b.ToTable("Genre", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Publisher");

                    b.ToTable("Publisher", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Rating", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int?>("Star1")
                        .HasColumnType("int")
                        .HasColumnName("star_1");

                    b.Property<int?>("Star2")
                        .HasColumnType("int")
                        .HasColumnName("star_2");

                    b.Property<int?>("Star3")
                        .HasColumnType("int")
                        .HasColumnName("star_3");

                    b.Property<int?>("Star4")
                        .HasColumnType("int")
                        .HasColumnName("star_4");

                    b.Property<int?>("Star5")
                        .HasColumnType("int")
                        .HasColumnName("star_5");

                    b.Property<double?>("StarsAverage")
                        .HasColumnType("float")
                        .HasColumnName("stars_average");

                    b.Property<int?>("StarsTotal")
                        .HasColumnType("int")
                        .HasColumnName("stars_total");

                    b.HasKey("BookId")
                        .HasName("PK__Rating");

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Readlist", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.HasKey("BookId", "UserId")
                        .HasName("PK__Readlist");

                    b.HasIndex("UserId");

                    b.ToTable("Readlist", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Review");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Setting");

                    b.ToTable("Setting", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("refresh_token");

                    b.HasKey("Id")
                        .HasName("PK__Token");

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImg")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("profile_img");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.UserRating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("UserId", "BookId")
                        .HasName("PK__UserRating");

                    b.HasIndex("BookId");

                    b.ToTable("UserRating", (string)null);
                });

            modelBuilder.Entity("Server.API.Models.Entities.Wishlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "BookId")
                        .HasName("PK__Wishlist");

                    b.HasIndex("BookId");

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("BookAward", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Award", null)
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Award__Award");

                    b.HasOne("Server.API.Models.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Award__Book");
                });

            modelBuilder.Entity("BookCharacter", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Character__Book");

                    b.HasOne("Server.API.Models.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Character__Character");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Genre__Book");

                    b.HasOne("Server.API.Models.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Genre__Genre");
                });

            modelBuilder.Entity("BookSetting", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Setting__Book");

                    b.HasOne("Server.API.Models.Entities.Setting", null)
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Book_Settings__Setting");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Book", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Book_Publisher");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Rating", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", "Book")
                        .WithOne("Rating")
                        .HasForeignKey("Server.API.Models.Entities.Rating", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Rating__Book");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Readlist", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", "Book")
                        .WithMany("Readlists")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Readlist__Book");

                    b.HasOne("Server.API.Models.Entities.User", "User")
                        .WithMany("Readlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Readlist__User");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Review", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Review__Book");

                    b.HasOne("Server.API.Models.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Review__User");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Token", b =>
                {
                    b.HasOne("Server.API.Models.Entities.User", "IdNavigation")
                        .WithOne("Token")
                        .HasForeignKey("Server.API.Models.Entities.Token", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Token__User");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Server.API.Models.Entities.UserRating", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", "Book")
                        .WithMany("UserRatings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRating__Book");

                    b.HasOne("Server.API.Models.Entities.User", "User")
                        .WithMany("UserRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserRating__User");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Wishlist", b =>
                {
                    b.HasOne("Server.API.Models.Entities.Book", "Book")
                        .WithMany("Wishlists")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Wishlist__Book");

                    b.HasOne("Server.API.Models.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Wishlist__User");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Book", b =>
                {
                    b.Navigation("Rating");

                    b.Navigation("Readlists");

                    b.Navigation("Reviews");

                    b.Navigation("UserRatings");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Server.API.Models.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Server.API.Models.Entities.User", b =>
                {
                    b.Navigation("Readlists");

                    b.Navigation("Reviews");

                    b.Navigation("Token");

                    b.Navigation("UserRatings");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
